name = "Intersections"
uuid = "6d0fbc77-481e-44fe-9ace-1653ddcdea34"
authors = ["Eric S. Tellez <donsadit@gmail.com> and contributors"]
version = "0.2.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
